name: bigscape
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - biopython=1.81
  - sortedcontainers=2.4.0
  - fasttree=2.1.11
  - numpy=1.26.0
  - pandas=2.1.1
  - pyhmmer=0.10.14
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - sqlalchemy=2.0.2
  - matplotlib=3.8.0
  - requests=2.31.0
  - tqdm=4.66.1
  - pip=23.3
  - pip:
    - click==8.1.7
    - PyYAML==6.0.1
    - importlib-metadata==8.5.0
