name: Run tests

on:
  push:
    branches:
      - master
      - dev
      - release/*
      - feature/*
      - hotfix/*

jobs:
  run_pytest:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs') && !contains(github.event.head_commit.message, 'documentation')  }}
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up mamba environment
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: environment.yml
        environment-name: BiG-SCAPE
        init-shell: bash
        generate-run-shell: true

    - name: Install dependencies
      shell: micromamba-shell {0}
      run: |
        python -m pip install pytest

    - name: Test with Pytest
      shell: micromamba-shell {0}
      run: |
        pytest
